server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pai?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: pai
    password: pai

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
