spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/pai
    username: pai
    password: pai

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      lettuce:
        pool:
          # 最小空闲连接数
          min-idle: 10
          # 最大空闲连接数
          max-idle: 20
          # 最大活跃连接数
          max-active: 20
          # 最大等待时间
          max-wait: 2000

# Knife4j 增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    swagger-model-name: '实体类列表'
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 'Apache License 2.0 | Copyright  2025 - [杰普软件科技有限公司]'


# 用于文件上传的目录 只要配置成本地的nginx即可 pai-file-nginx
# 自定义上传配置
upload:
  nginx-file-path: E:/nginx/pai-file-nginx/html # 图片真实存在目录
  nginx-server: http://localhost:89 # nginx的访问前缀
  file-directory-name: file # 文件压缩包存在的目录
  chunk-directory-name: chunk # 文件存在的目录
  #在nginx前缀拼接上文件名时才可以访问到该文件