server:
  port: 8888
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5      # 最小连接数
      max-active: 20   # 最大连接数
      initial-size: 5  # 初始化连接数
      max-wait: 60000  # 最大等待时间
mybatis-plus:
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
  # 设置类型别名
  type-aliases-package: com.briup.pai.entity
  # mapper映射文件所在位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      # 逻辑删除字段
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1