spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/pai
    username: pai
    password: pai

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      lettuce:
        pool:
          # 最小空闲连接数
          min-idle: 10
          # 最大空闲连接数
          max-idle: 20
          # 最大活跃连接数
          max-active: 20
          # 最大等待时间
          max-wait: 2000

# Knife4j 增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    swagger-model-name: '实体类列表'
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 'Apache License 2.0 | Copyright  2025 - [杰普软件科技有限公司]'